language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir build
  - cd build
  - wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz
  - tar zvfx cmake-3.5.2-Linux-x86_64.tar.gz
  - ./cmake-3.5.2-Linux-x86_64/bin/cmake ..
script:
  - make
  - ./unittests/all_unittests
